# Generated by Django 4.2.1 on 2023-06-30 14:50

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_reviewrating_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="modified_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="reviewrating",
            name="created_at",
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="reviewrating",
            name="update_at",
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
    ]
