# Generated by Django 4.2.1 on 2023-06-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_product_modified_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewrating",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="reviewrating",
            name="update_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
