# Generated by Django 4.2.3 on 2023-07-11 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_productgallery"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productgallery",
            options={
                "verbose_name": ("productgallery",),
                "verbose_name_plural": "product gallery",
            },
        ),
    ]
