# Generated by Django 4.2.3 on 2023-07-13 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0005_maincategory_alter_category_options_and_more"),
        ("store", "0008_alter_productgallery_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="category.maincategory"
            ),
        ),
    ]
