# Generated by Django 4.2.3 on 2023-07-14 07:12


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0007_alter_category_main_category_alter_category_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0010_section_product_discount_product_product_information_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandsName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name="additional_infomation",
            name="detail",
            field=models.CharField(max_length=100, verbose_name="جزئیات"),
        ),
        migrations.AlterField(
            model_name="additional_infomation",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="store.product",
                verbose_name="کالا",
            ),
        ),
        migrations.AlterField(
            model_name="additional_infomation",
            name="specification",
            field=models.CharField(max_length=100, verbose_name="مشخصات"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="category.category",
                verbose_name="دسته بندی",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True, max_length=500, verbose_name="توضیحات"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.IntegerField(null=True, verbose_name="تخفیف"),
        ),
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.ImageField(upload_to="photos/products", verbose_name="عکس ها"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_available",
            field=models.BooleanField(default=True, verbose_name="موجود"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(verbose_name="قیمت"),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_information",
            field=models.TextField(null=True, verbose_name="اطلاعات کالا"),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="نام کالا"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="section",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="store.section",
                verbose_name="قسمت",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.IntegerField(verbose_name="موجودی"),
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.CharField(max_length=100, null=True, verbose_name="تگ"),
        ),
        migrations.AlterField(
            model_name="productgallery",
            name="image",
            field=models.ImageField(
                max_length=225, upload_to="store/products", verbose_name="عکس"
            ),
        ),
        migrations.AlterField(
            model_name="productgallery",
            name="product",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.product",
                verbose_name="کالا",
            ),
        ),
        migrations.AlterField(
            model_name="reviewrating",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="store.product",
                verbose_name="کالا",
            ),
        ),
        migrations.AlterField(
            model_name="reviewrating",
            name="rating",
            field=models.FloatField(verbose_name="رتبه بندی"),
        ),
        migrations.AlterField(
            model_name="reviewrating",
            name="review",
            field=models.TextField(blank=True, max_length=500, verbose_name="دیدگاه"),
        ),
        migrations.AlterField(
            model_name="reviewrating",
            name="status",
            field=models.BooleanField(default=True, verbose_name="وضعیت"),
        ),
        migrations.AlterField(
            model_name="reviewrating",
            name="subject",
            field=models.CharField(blank=True, max_length=256, verbose_name="موضوع"),
        ),
        migrations.AlterField(
            model_name="reviewrating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر ",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="name",
            field=models.CharField(max_length=100, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="variation",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال"),
        ),
        migrations.AlterField(
            model_name="variation",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="store.product",
                verbose_name="کالا",
            ),
        ),
        migrations.AlterField(
            model_name="variation",
            name="variation_category",
            field=models.CharField(
                choices=[("color", "color"), ("size", "size")],
                max_length=100,
                verbose_name="دسته بندی تنوع",
            ),
        ),
        migrations.AlterField(
            model_name="variation",
            name="variation_value",
            field=models.CharField(max_length=100, verbose_name="مقدار تنوع"),
        ),
    ]
