# Generated by Django 4.2.3 on 2023-07-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_product_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="توضیحات"
            ),
        ),
    ]
