# Generated by Django 4.2.3 on 2023-07-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_alter_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_information",
            field=models.TextField(blank=True, null=True, verbose_name="اطلاعات کالا"),
        ),
    ]
