# Generated by Django 4.2.3 on 2023-07-15 17:38

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_alter_product_product_information"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=django_quill.fields.QuillField(
                blank=True, null=True, verbose_name="توضیحات"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_information",
            field=django_quill.fields.QuillField(
                blank=True, null=True, verbose_name="اطلاعات کالا"
            ),
        ),
    ]
