# Generated by Django 4.2.3 on 2023-07-31 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0008_alter_subcategory_slug"),
        ("store", "0015_alter_product_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sub_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="category.subcategory",
                verbose_name="دسته بندی",
            ),
        ),
    ]
