# Generated by Django 4.2.3 on 2023-08-06 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0018_slider"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slider",
            name="brand_name",
        ),
        migrations.RemoveField(
            model_name="slider",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="slider",
            name="like",
        ),
        migrations.RemoveField(
            model_name="slider",
            name="sale",
        ),
        migrations.AddField(
            model_name="slider",
            name="product",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.product",
                verbose_name="کالا",
            ),
        ),
        migrations.AlterField(
            model_name="slider",
            name="discount_deal",
            field=models.CharField(
                choices=[
                    ("پیشنهاد ویژه", "پیشنهاد ویژه"),
                    ("جدیدترین ها", "جدیدترین ها"),
                ],
                default=0,
                max_length=100,
            ),
        ),
    ]
