# Generated by Django 4.2.3 on 2023-09-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0019_remove_slider_brand_name_remove_slider_discount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="section",
            old_name="name",
            new_name="name_show",
        ),
        migrations.AddField(
            model_name="section",
            name="name_filter",
            field=models.CharField(
                default="", max_length=100, verbose_name="نام برای فیلتر کردن"
            ),
        ),
    ]
