# Generated by Django 4.2.3 on 2023-09-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0020_rename_name_section_name_show_section_name_filter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="name_filter",
            field=models.CharField(
                default="0", max_length=100, verbose_name="نام برای فیلتر کردن"
            ),
        ),
    ]
