# Generated by Django 4.2.3 on 2023-09-07 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0022_alter_section_name_filter"),
    ]

    operations = [
        migrations.RenameField(
            model_name="section",
            old_name="name_show",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="section",
            name="name_filter",
        ),
    ]
