# Generated by Django 4.2.3 on 2023-09-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0023_rename_name_show_section_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="name_show",
            field=models.CharField(
                default="null", max_length=100, verbose_name="نام_جهت نمایش"
            ),
        ),
    ]
