# Generated by Django 4.2.1 on 2023-06-11 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0002_cartitem_variation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="data_add",
            new_name="date_add",
        ),
    ]
