# Generated by Django 4.2.1 on 2023-06-24 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0004_cartitem_uer_alter_cartitem_cart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="uer",
            new_name="user",
        ),
    ]
