# Generated by Django 4.2.3 on 2023-08-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0006_alter_cartitem_is_active_alter_cartitem_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="shipping_cost",
            field=models.IntegerField(default=38000, verbose_name="هزینه حمل و نقل"),
        ),
    ]
