# Generated by Django 4.2.3 on 2023-09-13 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_blogdetails_description_blogdetails_img_banner_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogdetails",
            name="img_banner",
        ),
    ]
