# Generated by Django 4.2.3 on 2023-09-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_remove_blogdetails_img_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogdetails",
            name="img_banner",
            field=models.ImageField(
                null=True,
                upload_to="blogs/blog_details_banner",
                verbose_name="تصویر بنر بلاگ",
            ),
        ),
    ]
