# Generated by Django 4.2.3 on 2023-09-15 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0009_maincategory_belongs_to"),
        ("blogs", "0005_alter_blogdetails_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogdetails",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="category.category",
            ),
        ),
        migrations.AddField(
            model_name="blogdetails",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                db_collation="utf8_persian_ci",
                max_length=250,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="blogdetails",
            name="sub_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="category.subcategory",
            ),
        ),
    ]
