# Generated by Django 4.2.3 on 2023-09-16 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0007_alter_blogdetails_subject"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogdetails",
            options={
                "verbose_name": ("blogdetails",),
                "verbose_name_plural": "Blog Details",
            },
        ),
    ]
