# Generated by Django 4.2.3 on 2023-09-16 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0010_blogmaincategory_remove_maincategory_belongs_to_and_more"),
        ("blogs", "0008_alter_blogdetails_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogdetails",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="category.blogcategory",
            ),
        ),
        migrations.AlterField(
            model_name="blogdetails",
            name="sub_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="category.blogsubcategory",
            ),
        ),
    ]
