# Generated by Django 4.2.3 on 2023-09-17 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0009_alter_blogdetails_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogdetails",
            name="sub_category",
        ),
    ]
