# Generated by Django 4.2.3 on 2023-09-22 13:23

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("blogs", "0010_remove_blogdetails_sub_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogdetails",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
