# Generated by Django 4.2.3 on 2023-07-13 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_subcategory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SubCategory",
        ),
    ]
