# Generated by Django 4.2.3 on 2023-07-13 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0005_maincategory_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "category", "verbose_name_plural": "categories"},
        ),
    ]
