# Generated by Django 4.2.3 on 2023-07-14 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0006_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="main_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="category.maincategory",
                verbose_name="دسته بندی اصلی",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="maincategory",
            name="cat_image",
            field=models.ImageField(
                blank=True, upload_to="photos/categories", verbose_name="عکس دسته بندی"
            ),
        ),
        migrations.AlterField(
            model_name="maincategory",
            name="description",
            field=models.CharField(
                blank="True", max_length=255, verbose_name="توضیحات"
            ),
        ),
        migrations.AlterField(
            model_name="maincategory",
            name="name",
            field=models.CharField(default="null", max_length=100, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="category.category",
                verbose_name="دسته بندی",
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="name",
            field=models.CharField(max_length=100, verbose_name="نام"),
        ),
    ]
