# Generated by Django 4.2.3 on 2023-07-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0007_alter_category_main_category_alter_category_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcategory",
            name="slug",
            field=models.SlugField(allow_unicode=True, max_length=100, unique=True),
        ),
    ]
