# Generated by Django 4.2.3 on 2023-09-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0008_alter_subcategory_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="maincategory",
            name="belongs_to",
            field=models.CharField(
                choices=[("store", "فروشگاه"), ("blogs", "بلاگ")],
                default="store",
                max_length=100,
                verbose_name="متعلق به ",
            ),
        ),
    ]
