# Generated by Django 4.2.3 on 2023-09-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0010_blogmaincategory_remove_maincategory_belongs_to_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogcategory",
            options={
                "verbose_name": "blogcategory",
                "verbose_name_plural": "blog categories",
            },
        ),
        migrations.AlterField(
            model_name="blogcategory",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                db_collation="utf8_persian_ci",
                max_length=250,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="blogmaincategory",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                db_collation="utf8_persian_ci",
                max_length=250,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="blogsubcategory",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                db_collation="utf8_persian_ci",
                max_length=250,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                db_collation="utf8_persian_ci",
                max_length=250,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="maincategory",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                db_collation="utf8_persian_ci",
                max_length=250,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                db_collation="utf8_persian_ci",
                max_length=250,
                null=True,
                unique=True,
            ),
        ),
    ]
