# Generated by Django 4.2.3 on 2023-09-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "category",
            "0011_alter_blogcategory_options_alter_blogcategory_slug_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcategory",
            name="name",
            field=models.CharField(
                db_collation="utf8_persian_ci",
                max_length=100,
                unique=True,
                verbose_name="نام",
            ),
        ),
        migrations.AlterField(
            model_name="blogmaincategory",
            name="name",
            field=models.CharField(
                db_collation="utf8_persian_ci",
                default="null",
                max_length=100,
                unique=True,
                verbose_name="نام",
            ),
        ),
        migrations.AlterField(
            model_name="blogsubcategory",
            name="name",
            field=models.CharField(
                db_collation="utf8_persian_ci",
                max_length=100,
                unique=True,
                verbose_name="نام",
            ),
        ),
    ]
