# Generated by Django 4.2.3 on 2023-09-17 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "category",
            "0012_alter_blogcategory_name_alter_blogmaincategory_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogcategory",
            name="main_category",
        ),
        migrations.RemoveField(
            model_name="blogsubcategory",
            name="category",
        ),
        migrations.AddField(
            model_name="blogcategory",
            name="blog_main_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="category.blogmaincategory",
                verbose_name="دسته بندی اصلی",
            ),
        ),
        migrations.AddField(
            model_name="blogsubcategory",
            name="blog_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="category.blogcategory",
                verbose_name="دسته بندی",
            ),
        ),
    ]
