# Generated by Django 4.2.3 on 2023-09-17 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0010_remove_blogdetails_sub_category"),
        ("category", "0013_remove_blogcategory_main_category_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlogSubCategory",
        ),
    ]
