# Generated by Django 4.2.3 on 2023-10-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0015_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="photos/banner_sub_category",
                verbose_name="عکس بنر برای صفحه اصلی",
            ),
        ),
    ]
