# Generated by Django 4.2.3 on 2023-10-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0016_subcategory_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="description_update_image",
            field=models.TextField(
                default="272*140", max_length=512, verbose_name="توضیحات بارگیری عکس "
            ),
        ),
    ]
