# Generated by Django 4.2.1 on 2023-06-27 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="adress",
            new_name="address",
        ),
    ]
