# Generated by Django 4.2.1 on 2023-06-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_rename_adress_order_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="zip_code",
            field=models.CharField(default="0", max_length=15),
        ),
    ]
