# Generated by Django 4.2.3 on 2023-07-14 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_product_brand"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0004_alter_order_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(max_length=256, verbose_name="نشانی گیرنده"),
        ),
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(max_length=70, verbose_name="ایمیل"),
        ),
        migrations.AlterField(
            model_name="order",
            name="first_name",
            field=models.CharField(max_length=70, verbose_name="نام"),
        ),
        migrations.AlterField(
            model_name="order",
            name="is_ordered",
            field=models.BooleanField(default=False, verbose_name="سفارش داده شده"),
        ),
        migrations.AlterField(
            model_name="order",
            name="last_name",
            field=models.CharField(max_length=70, verbose_name="نام خانوادگی"),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_note",
            field=models.CharField(max_length=100, null=True, verbose_name="متن سفارش"),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(max_length=100, verbose_name="شماره سفارش"),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_total",
            field=models.FloatField(verbose_name="تعداد سفارش"),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orders.payment",
                verbose_name="پرداخت",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(max_length=15, verbose_name="تلفن"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "جدید"),
                    ("Accepted", "پذیرفته شده"),
                    ("Completed", "تکمیل شده"),
                    ("Cancelled", "لغو شئده"),
                ],
                default="New",
                max_length=20,
                verbose_name="وضعیت",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="zip_code",
            field=models.CharField(default="0", max_length=15, verbose_name="کد پستی"),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="Payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orders.payment",
                verbose_name="پرداخت",
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="color",
            field=models.CharField(max_length=70, verbose_name=" رنگ"),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.order",
                verbose_name="سفارش",
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="ordered",
            field=models.BooleanField(default=False, verbose_name="سفارش داده شده"),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="store.product",
                verbose_name="کالا",
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="product_price",
            field=models.FloatField(verbose_name="هزینه کالا"),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="quantity",
            field=models.IntegerField(verbose_name="تعداد"),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="size",
            field=models.CharField(max_length=50, verbose_name="سایز"),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
        migrations.AlterField(
            model_name="orderproduct",
            name="variation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="store.variation",
                verbose_name="تنوع",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount_paid",
            field=models.CharField(max_length=100, verbose_name="مقدار پرداخت"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="زمان  ایجاد"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_id",
            field=models.CharField(max_length=100, verbose_name="شناسه پرداخت"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(max_length=100, verbose_name="روش پرداخت"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(max_length=100, verbose_name="وضعیت"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
    ]
